Enhance venv activation script with error handling
Final.
added red to venv and .venv if not found. 
Cleaned up a little.

diff --git a/venv_activate b/venv_activate
--- a/venv_activate
+++ b/venv_activate
@@ -2,44 +2,48 @@
 
 Color_Off='\033[0m'
 BGreen='\033[1;32m'
-nl=$'\n'
+BRed='\033[1;31m'
 
 venv_activate() {
     enjoy() {
         echo -e "Enjoy working on your $(basename "$PWD") project, ${USER^}!"
-        printf '*%.0s' {1..80}
-
+        echo
     }
 
-
-   spin_up() {
-        if [ -n "$1" ]; then #Check if a virtual environment path is provided.
-            bash -c "source $1/bin/activate; exec bash -i" || echo "Failed to activate: $1"
+    spin_up() {
+        if [ -n "$1" ]; then
+            if [ -f "$1/bin/activate" ]; then
+                echo "Launching a new Bash shell with the virtual environment activated."
+                bash -c "source \"$1/bin/activate\"; exec bash -i" || echo "Failed to activate: $1"
+            else
+                echo "Error: '$1/bin/activate' not found." >&2
+                return 2
+            fi
         else
             echo "Error: No virtual environment path provided to spin_up." >&2
             return 1
         fi
     }
 
-
-    if [ -d "$PWD/.venv" ]; then ${nl}
-        printf '*%.0s' {1..80}
-        echo  -e "${nl}$BGreen .venv$Color_Off found in: $PWD  |  $BGreen .venv$Color_Off activated.${nl}"
+    if [ -d "$PWD/.venv" ]; then
+        echo -e "${BGreen}.venv${Color_Off} found in: $PWD"
+        echo -e "${BGreen}.venv${Color_Off} activated."
         venv_path="$PWD/.venv"
         enjoy
         spin_up "$venv_path"
-        return 0
+        return $?
     elif [ -d "$PWD/venv" ]; then
-        printf '*%.0s' {1..80}
-        echo -e "${nl}$BGreen venv$Color_Off found in: $PWD  | $BGreen venv$Color_Off activated.${nl}"
+        echo -e "${BGreen}venv${Color_Off} found in: $PWD"
+        echo -e "${BGreen}venv${Color_Off} activated."
         venv_path="$PWD/venv"
         enjoy
         spin_up "$venv_path"
-        return 0
+        return $?
     else
-        echo -e "Error: No 'venv' or '.venv' directory found." >&2
-        return 1  # Indicate failure
+        echo -e "Error: No ${BRed}venv${Color_Off} or ${BRed}.venv$Color_Off directory found." >&2
+        return 1
     fi
 
-
 }
+
+venv_activate
